spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://XXX:3306/ordersystem
    username: XXXX
    password: YYYY

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    show_sql: false
    hibernate:
      ddl-auto: update


  redis:
    host: XXXX
    port: 6379

  config:
    activate:
      on-profile: prod

jwt:
  expirationAt: 1000
  secretKeyAt: XXX
  expirationRt: 10000
  secretKeyRt: YYY
  adminEmail: xx
  adminPassword: yy

cloud:
  aws:
    credentials:
      access-key: XX
      secret-key: YY
    region:
      static: ap-northeast-2
    s3:
      bucket: xx
server:
  port: 8080

